title: Sara Gong
description: Undergrad majoring in economics, math, and philosophy at USC and conducting research on entrepreneurial decision-making at Columbia. Los Angeles, CA.
logo: /assets/jpg/logo.jpg
theme: jekyll-theme-minimal

# variables for jekyll-seo-tag
url: https://saragong.github.io/
author: Sara Gong
twitter:
  username: notsaragong
  card: summary
google_site_verification: UA-147633665-1

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock