title: Sara Gong
email: saragong@usc.edu
description: > 
  Economics, math, and philosophy at USC. Conducting research on entrepreneurial 
  decision-making at Columbia Business School. Los Angeles, California.
baseurl: ""
url: "https://saragong.github.io/"
github_username:  saragong
author: sara gong
linkedin: saragong

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

