theme: jekyll-theme-minimal
title: sara gong
description:
university of southern california '21
b.s. economics/math
b.a. philosophy

conducting research on entrepreneurial decision-making at Columbia Business School. former Congressional intern experienced in legislative issues, campaigns, and activism. interested in development and behavioral economics, and fascinated by problems at the intersection of policy, rationality, and uncertainty.

currently in London.